# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# Please consult the lectures

"""
A Vector is a one-dimensional array that holds multiple elements in a single row or column.
A Matrix is a two-dimensional array that contains elements arranged in rows and columns. 
It can also be extended to higher dimensions (3D, 4D, etc.) for more complex data structures.
"""

**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 
import numpy as np

In [3]:
print(np.__version__)

2.2.6


**3. Convert the given Python list into NumPy array and check its data type**

In [5]:
list_1 = [1,2,3,4,5]

In [7]:
# To avoid overwriting the output, please code here 
np_list = np.array(list_1)
np_list

array([1, 2, 3, 4, 5])

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [9]:
# To avoid overwriting the output, please code here 
np_array = np.arange(6)
np_array

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [12]:
# To avoid overwriting the output, please code here 
np_zeros = np.zeros(5)
np_zeros

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [19]:
# To avoid overwriting the output, please code here 
np_matrix = np.zeros(12).reshape(3,4)
np_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [20]:
# To avoid overwriting the output, please code here 
np_ones = np.ones(5)
np_ones

array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [22]:
# To avoid overwriting the output, please code here 
np_array_of_10 = np.full(5, fill_value=10)
np_array_of_10

array([10, 10, 10, 10, 10])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [25]:
# To avoid overwriting the output, please code here 
np_array_of_even = np.arange(50, 100, 2)
np_array_of_even

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [43]:
# To avoid overwriting the output, please code here 

np_linspace = np.linspace(0, 1, num=10, retstep=True)
np_linspace

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [44]:
# To avoid overwriting the output, please code here 
vector_array = np.arange(25)
vector_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
# To avoid overwriting the output, please code here 
vector_array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
# To avoid overwriting the output, please code here 
vector_array.shape = (5, 5)
vector_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [68]:
# To avoid overwriting the output, please code here 
np_of_matrix = np.arange(0.1, 2.6, 0.1)
np_of_matrix.reshape(5,5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [92]:
# To avoid overwriting the output, please code here 
np_lineSpace = np.linspace(0, 25, num=25, dtype=np.int64)
print(np_lineSpace.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 25]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

"""
The main difference between 'arange()' and 'linspace()' is that arange() 
generates values with a specific step size between them, 
And the other hand --> linspace() generates a specific number of evenly spaced 
points between the start and stop values.
"""

**15. How to generate a single random integer number using NumPy built-in function?**

In [163]:
# To avoid overwriting the output, please code here 
np_random_num = np.random.randint(1, 10)
np_random_num

4

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [190]:
# To avoid overwriting the output, please code here 
np_rand_matrix = np.random.rand(35)
print(np_rand_matrix.reshape(7,5))

[[0.95835198 0.79171455 0.31998734 0.66676634 0.24776541]
 [0.75762423 0.55065866 0.05848455 0.98875169 0.25184341]
 [0.93201531 0.35128462 0.14985254 0.21455516 0.83607151]
 [0.86120614 0.10891826 0.85249885 0.89082496 0.64614169]
 [0.6449893  0.37674167 0.98218323 0.95559661 0.42346855]
 [0.47924771 0.19334262 0.52067646 0.11812887 0.19758117]
 [0.41275397 0.58198268 0.93015989 0.90516798 0.72529656]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [205]:
# To avoid overwriting the output, please code here 
identity_matrix = 5 * np.eye(5)
identity_matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 